# CMake generated Testfile for 
# Source directory: /home/hla294/Desktop/cmpt479/parabix-devel
# Build directory: /home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(greptest "python3" "greptest.py" "--random_flag_count=2" "--tests_per_grepcase=2" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/icgrep")
set_tests_properties(greptest PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;459;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(proptest "python3" "greptest.py" "-d" "/home/hla294/Desktop/cmpt479/parabix-devel/QA" "-t" "/home/hla294/Desktop/cmpt479/parabix-devel/QA/proptest.xml" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/icgrep")
set_tests_properties(proptest PROPERTIES  TIMEOUT "1500" WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;464;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(abc_test "./run_abc" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/icgrep")
set_tests_properties(abc_test PROPERTIES  TIMEOUT "100" WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;475;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(u8u16_test "./run_all" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/u8u16 -thread-num=2")
set_tests_properties(u8u16_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/u8u16" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;480;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(u32u8_test "./test_u32u8" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/u32u8")
set_tests_properties(u32u8_test PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;485;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(nfd_test "./test_nfd" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/nfd")
set_tests_properties(nfd_test PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/nfd" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;490;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(editd_test "python3" "run_all.py" "-e" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin")
set_tests_properties(editd_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/editd" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;495;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(base64_test "python3" "base64test.py" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/base64")
set_tests_properties(base64_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/base64" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;500;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(gb18030_test "./run_all" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/gb18030")
set_tests_properties(gb18030_test PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/gb18030" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;505;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(json_test "./run_all" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/json")
set_tests_properties(json_test PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/json" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;510;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
add_test(csv2json_test "./run_csv2json" "/home/hla294/Desktop/cmpt479/parabix-devel/transliterator_compiler/bin/csv2json")
set_tests_properties(csv2json_test PROPERTIES  WORKING_DIRECTORY "/home/hla294/Desktop/cmpt479/parabix-devel/QA/csv/csv2json" _BACKTRACE_TRIPLES "/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;515;add_test;/home/hla294/Desktop/cmpt479/parabix-devel/CMakeLists.txt;0;")
subdirs("lib/codegen")
subdirs("lib/fileselect")
subdirs("lib/grep")
subdirs("lib/idisa")
subdirs("lib/kernel/core")
subdirs("lib/kernel/pipeline")
subdirs("lib/objcache")
subdirs("lib/pablo")
subdirs("lib/pablo/bixnum")
subdirs("lib/pablo/parse")
subdirs("lib/re/adt")
subdirs("lib/re/analysis")
subdirs("lib/re/cc")
subdirs("lib/re/compile")
subdirs("lib/re/parse")
subdirs("lib/re/printer")
subdirs("lib/re/toolchain")
subdirs("lib/re/transforms")
subdirs("lib/re/unicode")
subdirs("lib/testing")
subdirs("lib/toolchain")
subdirs("lib/unicode/algo")
subdirs("lib/unicode/core")
subdirs("lib/unicode/data")
subdirs("lib/unicode/utf")
subdirs("lib/kernel/basis")
subdirs("lib/kernel/bitwise")
subdirs("lib/kernel/io")
subdirs("lib/kernel/scan")
subdirs("lib/kernel/streamutils")
subdirs("lib/kernel/unicode")
subdirs("lib/kernel/util")
subdirs("lib/kernel/illustrator")
subdirs("tools/base64")
subdirs("tools/editd")
subdirs("tools/icgrep")
subdirs("tools/idisa_test")
subdirs("tools/json")
subdirs("tools/transcoders")
subdirs("tools/wc")
subdirs("tools/xml")
subdirs("tools/ztf8")
subdirs("tools/util")
subdirs("tools/csv")
subdirs("tests")
